### ISSUE TITLE
Bug / wrong picture

### ISSUE THREAD

**Issue by Leo22117311** [EpicSevenDB/ui#23]
Kise and judge kise skills are all swapped, the pictures.
How do u post a picture if the issue is already uploaded

**Comment by RaphaelDDL** [comment]
Hello there :D  

Oh wow, never noticed that, probably because I don't have either of them TT___TT

Now, funny story:
![image](https://user-images.githubusercontent.com/1087109/59439715-211e7600-8dcc-11e9-902c-e41d46c3eb15.png)
![Screen Shot 2019-06-13 at 11 09 48 AM](https://user-images.githubusercontent.com/1087109/59439771-38f5fa00-8dcc-11e9-8d5e-c8bffd77e41b.png)

I double checked the datamined images I have, and actually SG who messed up the skills lol. Judge Kise (id c2006) has Kise's (c1006) skills, and vice-versa :O 

Nevertheless, I fixed here on my end. Should be fixed in few mins when image cache expires.

Thank you for noticing :)


_PS: To post a screenshot after posting the issue, you can click on the upper right 3 dots image on your post, choose edit and then paste the image inside the textarea, github already uploads and links for you :)_

**Comment by Leo22117311** [comment]
Thank you for changing it and thanks for your hard work in making this
app/game info, it helps me out, especially with labyrinth morale :DD
